# Generated by Django 5.2.9 on 2025-12-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.TextField(blank=True, help_text='Comma-separated list of features for one-time setup plans'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('monthly', 'Monthly Subscription'), ('one_time', 'One-Time Setup')], default='monthly', max_length=20),
        ),
    ]
