# Generated by Django 5.2.9 on 2025-12-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_subscriptionplan_features_subscriptionplan_plan_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={},
        ),
    ]
