# Generated by Django 5.2.9 on 2025-12-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_subscriptionplan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='badge',
            field=models.CharField(blank=True, help_text="Optional badge like 'Most Popular'", max_length=50),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='highlighted',
            field=models.BooleanField(default=False, help_text='If True, visually emphasize this plan'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.TextField(blank=True, help_text='Comma-separated list of features'),
        ),
    ]
