# Generated by Django 5.2.9 on 2025-12-04 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_subscriptionplan_badge_subscriptionplan_highlighted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('summary', models.TextField(blank=True, help_text='Short intro shown in cards.')),
                ('content', models.TextField(help_text='Full documentation body (Markdown or HTML).')),
                ('read_time_minutes', models.PositiveIntegerField(default=5, help_text='Estimated read time (minutes).')),
                ('featured', models.BooleanField(default=False, help_text='If True, can be highlighted in the list.')),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('feature_image', models.ImageField(blank=True, null=True, upload_to='knowledge/images/')),
                ('video_url', models.URLField(blank=True, help_text='Optional link to YouTube/Vimeo/etc.')),
                ('video_file', models.FileField(blank=True, help_text='Optional uploaded video file.', null=True, upload_to='knowledge/videos/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='dashboard.knowledgecategory')),
            ],
            options={
                'ordering': ['sort_order', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='knowledge/attachments/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dashboard.knowledgearticle')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
