# Generated by Django 5.2.9 on 2025-12-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_client_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='body',
        ),
        migrations.AddField(
            model_name='message',
            name='business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='platform',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='problem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='urgency',
            field=models.CharField(blank=True, choices=[('Low', 'General Inquiry'), ('Medium', 'Issue affecting workflow'), ('High', 'Critical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
