# Generated by Django 5.2.9 on 2025-12-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
            ],
            options={
                'verbose_name': 'Contact Request',
                'verbose_name_plural': 'Contact Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dashboard.message',),
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dashboard.message',),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
